<?php
	//********************************************************************************************//
	//						COPYRIGHT: VOICETECH SOLUTIONS PVT LTD,								**
	//								      BANGALORE												**
	//********************************************************************************************
	//*********** FILE NAME: Inc_side_menu_definitions.php *************************************

	//*********************************** DESCRIPTION ********************************************
	//	Definitions Of  All Side Menus.							**
	//								    														**
	//********************************************************************************************
	//********************************* HISTORY **************************************************
	// Header created by: Makam on 19-03-2014 in release version: 2.0.0.22
		//Included All Side Menus
		//Formatted
	//last Modified by vikram report definitions on 16-oct-2014 in release20023 	
	//******************************** END OF HEADER *********************************************//	

	$ADMIN_SIDE_MENU_USER_MANAGER = "USER MANAGER";
	$ADMIN_SIDE_MENU_USER_MANAGER_NEW = "ACTIVE USERS";
	$ADMIN_SIDE_MENU_USER_MANAGER_DEFINE_NEW_USERTYPE = "SPECIAL USERS";
	$ADMIN_SIDE_MENU_USER_MANAGER_TERMINATION = "TERMINATE USERS";
	$ADMIN_SIDE_MENU_USER_MANAGER_DORMANT_USERS = "DORMANT USERS";

	$ADMIN_SIDE_MENU_INSTITUTE_WORKING_DAYS = "WORKING DAYS";
	$ADMIN_SIDE_MENU_FINANCIAL_YEAR_DEFINITIONS = "FINANCIAL";
	$ADMIN_SIDE_MENU_INSTITUTE_WORKING_DAYS_INSTITUTE = "INSTITUTE";
	$ADMIN_SIDE_MENU_INSTITUTE_WORKING_DAYS_COURSE = "CLASS COMMENCEMENT";
	
	$ADMIN_SIDE_MENU_DEPARTMENTS_AND_COURSES = "ACADEMIC INFRASTRUCTURE";
	$ADMIN_SIDE_MENU_DEPARTMENTS_AND_COURSES_DEPARTMENTS = "DEPARTMENT LIST";
	$ADMIN_SIDE_MENU_DEPARTMENTS_AND_COURSES_COURSES = "COURSE LIST";
	$ADMIN_SIDE_MENU_DEPARTMENTS_AND_COURSES_SECTIONS = "SECTION LIST";
	$ADMIN_SIDE_MENU_DEPARTMENTS_AND_COURSES_COURSE_SECTION_MAP = "COURSE AND SECTIONS";

	$ADMIN_SIDE_MENU_EXAM_TEMPLATES = "DEFINE CURRICULUM";
	$ADMIN_SIDE_MENU_DEPARTMENTS_AND_COURSES_SUBJECT_TYPES = "SUBJECT TYPES";
	$ADMIN_SIDE_MENU_DEPARTMENTS_AND_COURSES_SUBJECTS = "SUBJECTS";
	$ADMIN_SIDE_MENU_EXAM_TEMPLATES_MASTER_TEMPLATES = "MASTER TEMPLATES";
	$ADMIN_SIDE_MENU_EXAM_TEMPLATES_DEFINE_EXAM_TYPES = "DEFINE EXAM TYPES";
	$ADMIN_SIDE_MENU_EXAM_TEMPLATES_DEFINE_EXAMS = "DEFINE EXAMS";
	$ADMIN_SIDE_MENU_EXAM_TEMPLATES_EDIT_EXAMS = "EDIT EXAMS";

	$ADMIN_SIDE_MENU_ACADEMIC_DEFINITIONS = "ACADEMIC DEFINITIONS";
	$ADMIN_SIDE_MENU_ACADEMIC_DEFINITIONS_QUOTA = "QUOTA";
	$ADMIN_SIDE_MENU_ACADEMIC_DEFINITIONS_DESIGNATIONS = "DESIGNATIONS";
	$ADMIN_SIDE_MENU_ACADEMIC_DEFINITIONS_RELIGIONS = "RELIGIONS";
	$ADMIN_SIDE_MENU_ACADEMIC_DEFINITIONS_CATEGORY = "CATEGORY";

	$ADMIN_SIDE_MENU_ATTENDANCE_DEFINITIONS = "ATTENDANCE DEFINITIONS";
	$ADMIN_SIDE_MENU_ATTENDANCE_DEFINITIONS_STUDENT = "STUDENT";

	$ADMIN_SIDE_MENU_EVENTS_AND_HOLIDAYS = "ACADEMIC CALENDAR";
	$ADMIN_SIDE_MENU_EVENTS_AND_HOLIDAYS_ACADEMIC_EVENTS = "ACADEMIC EVENTS HOLIDAYS";
	$ADMIN_SIDE_MENU_MONTHLY_HOLIDAY_REPORT = "MONTHLY HOLIDAY REPORT";

	$ADMIN_SIDE_MENU_CONFIGURATION = "CONFIGURATION";
	$ADMIN_SIDE_MENU_CONFIGURATION_FRONT_SCREEN = "CONFIGURE DASH BOARD";

	$ADMIN_SIDE_MENU_EXPENSE = "EXPENSE";
	$ADMIN_SIDE_MENU_EXPENSE_MONTHLY_EXPENSE = "MONTHLY EXPENSE";
	//******************************************Elite Module*****************************//
	$ELITE_SIDE_MENU = "ELITE";
	$ELITE_SIDE_MENU_SELECT = "SELECT";
	$ELITE_SIDE_MENU_BASIC_INFORMATION = "BASIC INFORMATION";
	$ELITE_SIDE_MENU_PERSONAL_INFORMATION = "PERSONAL INFORMATION";
	$ELITE_SIDE_MENU_MESSAGE_INFORMATION = "MESSAGE INFORMATION";
	//*********************************Elite Module*********************************************//
	//******************************************Security Module*****************************//
	$SECURITY_SIDE_MENU = "SECURITY";
	$SECURITY_SIDE_MENU_MODULE_PERMISSIONS = "PERMISSIONS";
	$SECURITY_SIDE_MENU_MODULE_SECURITY = "MODULE SECURITY";
	$SECURITY_SIDE_MENU_REPORT_SECURITY = "REPORT SECURITY";
	$SECURITY_SIDE_MENU_USER_NAME_SECURITY = "USER NAME SECURITY";
	$SECURITY_SIDE_MENU_USER_LEVEL_PERMISSION = "USER LEVEL PERMISSION";
	$SECURITY_SIDE_MENU_FINE_COLLECTION_PERMISSION = "FINE COLLECTION PERMISSION";
	//*********************************Sandesh*********************************************//
	//******************************************Faculty Module*****************************//
	$FACULTY_SIDE_MENU_INFORMATION = "INFORMATION";
	$FACULTY_SIDE_MENU_SELECT_FACULTY = "SELECT FACULTY";
	$FACULTY_SIDE_MENU_BASIC = "BASIC";
	$FACULTY_SIDE_MENU_EDUCATION = "EDUCATION";
	$FACULTY_SIDE_MENU_FINANCE = "FINANCE";
	$FACULTY_SIDE_MENU_PERSONAL = "PERSONAL";
	$FACULTY_SIDE_MENU_EXPERIENCE = "EXPERIENCE";
	$FACULTY_SIDE_MENU_PROJECTS = "PROJECTS";
	$FACULTY_SIDE_MENU_PUBLICATIONS = "PUBLICATIONS";
	$FACULTY_SIDE_MENU_SELECT_SUBJECT = "SELECT SUBJECT";
	$FACULTY_SIDE_MENU_SUBJECT_WISE_REPORT = "SUBJECT WISE REPORT";
	$FACULTY_SIDE_MENU_FACULTY_EXAM_TEMPLATE = "FACULTY EXAM TEMPLATE";
	$FACULTY_SIDE_MENU_MAP_SUBJECT_WITH_TEMPLATE = "MAP SUBJECT WITH TEMPLATE";
	$FACULTY_SIDE_MENU_CUSTOM_TEMPLATE = "CUSTOM TEMPLATE";
	$FACULTY_SIDE_MENU_CUSTOM_EXAMS = "CUSTOM EXAM TYPES";
	$FACULTY_SIDE_MENU_CREATE_CUSTOM_TEMPLATE = "CUSTOM EXAMS";
	$FACULTY_SIDE_MENU_EDIT_CUSTOM_TEMPLATE = "EDIT CUSTOM EXAMS";
	$FACULTY_SIDE_MENU_MARKSLIST = "MARKLIST";
	$FACULTY_SIDE_MENU_INTERNAL = "INTERNAL";
	$FACULTY_SIDE_MENU_FINAL_INTERNAL = "FINAL INTERNAL";
	$FACULTY_SIDE_MENU_EXTERNAL = "EXTERNAL";
	$FACULTY_SIDE_MENU_SUBJECT_FINALIZATION = "FINALIZE SUBJECTS";
	$FACULTY_SIDE_MENU_UTILITY = "UTILITY";
	$FACULTY_SIDE_MENU_OPTIONAL_SUBJECT_FINALIZATION_ALLOCATION_GROUPS = "FINALIZE SUBJECTS";
	$FACULTY_SIDE_MENU_CHANGE_USERNAME = "CHANGE USERNAME";
	$FACULTY_SIDE_MENU_CHANGE_PASSWORD = "CHANGE PASSWORD";
	$FACULTY_SIDE_MENU_UPGRADATION = "UPGRADATION";
	$FACULTY_SIDE_MENU_STUDENT_UPGRADATION = "STUDENT UPGRADATION";
	//******************************************NTS Module*****************************//
	$NTS_SIDE_MENU_INFORMATION = "INFORMATION";
	$NTS_SIDE_MENU_SELECT_STAFF = "SELECT STAFF";
	$NTS_SIDE_MENU_BASIC = "BASIC";
	$NTS_SIDE_MENU_EDUCATION = "EDUCATION";
	$NTS_SIDE_MENU_FINANCE = "FINANCE";
	$NTS_SIDE_MENU_PERSONAL = "PERSONAL";
	$NTS_SIDE_MENU_EXPERIENCE = "EXPERIENCE";
	$NTS_SIDE_MENU_FEE = "FEE";
	$NTS_SIDE_MENU_ADMISSION = "ADMISSION";
	//******************************************Student Module*****************************//
	$STUDENT_SIDE_MENU_INFORMATION = "INFORMATION";
	$STUDENT_SIDE_MENU_SELECT_STUDENT = "SELECT STUDENT";
	$STUDENT_SIDE_MENU_BASIC = "BASIC INFO";
	$STUDENT_SIDE_MENU_FAMILY = "FAMILY INFO";
	$STUDENT_SIDE_MENU_PERSONAL = "PERSONAL INFO";
	$STUDENT_SIDE_MENU_SSLC = "SSLC";
	$STUDENT_SIDE_MENU_PUC = "PRE UNIVERSITY";
	$STUDENT_SIDE_MENU_DIPLOMA = "DIPLOMA";
	$STUDENT_SIDE_MENU_DEGREE = "DEGREE";
	$STUDENT_SIDE_MENU_CURRICULAR = "CURRICULAR ACTIVITIES";
	$STUDENT_SIDE_MENU_GENERALINFORMATION = "GENERAL INFORMATION";
	$STUDENT_SIDE_MENU_REMARKS = "REMARKS";
	$STUDENT_SIDE_MENU_FEEDBACKFORM = "FEED BACK FORM";
	$STUDENT_SIDE_MENU_ADMISSION = "ADMISSION DETAILS";
	$STUDENT_SIDE_MENU_ISSUEAPPLICATION = "ISSUE APPLICATION";
	$STUDENT_SIDE_MENU_MODIFYAPPLICATION = "MODIFY APPLICATION";
	$STUDENT_SIDE_MENU_ATTENDANCE = "ATTENDANCE";
	$STUDENT_SIDE_MENU_SEMESTERWISE = "SEMESTERWISE";
	$STUDENT_SIDE_MENU_STARTDATE = "FROM STARTDATE";
	$STUDENT_SIDE_MENU_WEEKTIMETABLE = "WEEK TIMETABLE";
	$STUDENT_SIDE_MENU_DETAILEDTIMETABLE = "DETAILED TIMETABLE";
	$STUDENT_SIDE_MENU_FEE = "FEE";
	$STUDENT_SIDE_MENU_FINE = "FINE";
	$STUDENT_SIDE_MENU_MARKLIST = "MARKLIST";
	$STUDENT_SIDE_MENU_ACADEMICCALENDER = "HOLIDAY LIST";
	$STUDENT_SIDE_MENU_FLEET="FLEET";
	$STUDENT_SIDE_MENU_FLEET_UPGRADATION="ALLOCATION";
	$STUDENT_SIDE_MENU_UTILITY = "UTILITY";
	$STUDENT_SIDE_MENU_CHANGE_USERNAME = "CHANGE USERNAME";
	$STUDENT_SIDE_MENU_CHANGE_PASSWORD = "CHANGE PASSWORD";
	$STUDENT_SIDE_MENU_FEE_CONCESSION = "FEE CONCESSION";
	$STUDENT_SIDE_MENU_CONFIRM_ADMISSION = "CONFIRM ADMISSION";
	$STUDENT_SIDE_MENU_TIMETABLE="TIMETABLE";
	//******************************************Timetable Module*****************************//
	$TIMETABLE_SIDE_CLASS = "SELECT CLASS";
	$TIMETABLE_SIDE_MENU_ALLOCATE_TT = "ALLOCATE TIMETABLE";
	$TIMETABLE_SIDE_MENU_FACULTYSUBJECTMAP = "FACULTY SUBJECT MAP";
	$TIMETABLE_SIDE_MENU_COMBINED = "COMBINED CLASS";
	$TIMETABLE_SIDE_MENU_SEGMENTED = "SEGMENTED CLASS";
	$TIMETABLE_SIDE_MENU_OPTIONAL = "OPTIONAL CLASS";
	$TIMETABLE_SIDE_MENU_REGULAR  = "REGULAR CLASS";
	$TIMETABLE_SIDE_MENU_VIEWTIMETABLE = "VIEW TIMETABLE";
	$TIMETABLE_SIDE_MENU_WEEKLY = "WEEKLY";
	$TIMETABLE_SIDE_MENU_DATEWISE = "DATE WISE";
	$TIMETABLE_SIDE_MENU_SCRIPT = "SCRIPT";
	$TIMETABLE_SIDE_MENU_MODIFY = "MODIFY TIMETABLE";
	$TIMETABLE_SIDE_MENU_SUBSTITUTION = "FACULTY SUBSTITUTION";
	$TIMETABLE_SIDE_MENU_DAYSUBSTITUTION = "DAY SUBSTITUTION";
	$TIMETABLE_SIDE_MENU_REPORTS = "REPORTS";
	$TIMETABLE_SIDE_MENU_HRS = "SUBJECT HOURS";
	$TIMETABLE_SIDE_MENU_FSH= "FACULTY SUBJECT HOURS";
	$TIMETABLE_SIDE_MENU_SSH = "STUDENT SUBJECT HOURS";
	
	//******************************************Attendance Module*****************************//
	$ATTENDANCE_SIDE_MENU = "ATTENDANCE";
	$ATTENDANCE_SIDE_MENU_CLASS = "CLASS";
	$ATTENDANCE_SIDE_MENU_STUDENT = "STUDENT";
	$ATTENDANCE_SIDE_MENU_FACULTY = "FACULTY";
	//******************************************MarksList Module*****************************//
	$MARKSLIST_SIDE_MENU = "MARKSLIST";
	$MARKSLIST_SIDE_MENU_SUBJECTWISE = "SUBJECTWISE MARKS ENTRY";
	$MARKSLIST_SIDE_MENU_FINALINTERNALMARKS = "FINAL INTERNAL MARKS";
	$MARKSLIST_SIDE_MENU_EXTERNAL = "EXTERNAL MARKS";
	$MARKSLIST_SIDE_MENU_ARREARLIST = "STUDENT ARREAR LIST";
	//******************************************Utility Module*****************************//
	$UTILITY_SIDE_MENU_UTILITY = "UTILITY";
	$UTILITY_SIDE_MENU_CUSERNAME = "CHANGE USERNAME";
	$UTILITY_SIDE_MENU_CPASSWORD = "CHANGE PASSWORD";
	$UTILITY_SIDE_MENU_RPASSWORD = "RESET PASSWORD";
	$UTILITY_SIDE_MENU_USERS = "LIST OF USERS";
	$UTILITY_SIDE_MENU_IMPORTCENTER = "IMPORT CENTER";
	$UTILITY_SIDE_MENU_IMPORTSTUDENT = "IMPORT STUDENT";
	$UTILITY_SIDE_MENU_IMPORTFACULTY = "IMPORT FACULTY";
	$UTILITY_SIDE_MENU_IMPORTSUBJECTS = "IMPORT SUBJECTS";
	$UTILITY_SIDE_MENU_SD_ED = "IMPORT SEMESTER START AND END DATES";
	//******************************************Fee Module*****************************//
	$FEE_SIDE_MENU_FEES = "DEFINITION";
	$FEE_SIDE_MENU_CATEGORY = "DEFINE FEE STRUCTURE";
	$FEE_SIDE_MENU_ALLOCATION = "ALLOCATION";
	$FEE_SIDE_MENU_FREQUENCY = "FREQUENCY";
	$FEE_SIDE_MENU_COURSEMAP = "ALLOCATE FEE";
	$FEE_SIDE_MENU_DEFINITION = "DEFINITION";
	$FEE_SIDE_MENU_CONFIRMATION = "CONFIRMATION";
	$FEE_SIDE_MENU_RECEIPTS = "RECEIPTS";
	$FEE_SIDE_MENU_RECEIPTTYPE = "TYPE";
	$FEE_SIDE_MENU_RECEIPTCATEGORY = "CATEGORY";
	$FEE_SIDE_MENU_RECEIPTDEFINITIONS = "DEFINITIONS";
	$FEE_SIDE_MENU_CLERKRECEIPTMAP = "CLERK RECEIPT MAP";
	$FEE_SIDE_MENU_CONCESSION = "CONCESSION";
	$FEE_SIDE_MENU_ACADEMICCONCESSION = "ACADEMIC";
	$FEE_SIDE_MENU_COLLECT = "COLLECTION";
	$FEE_SIDE_MENU_ACADEMIC = "COLLECT";
	$FEE_SIDE_MENU_FLEET = "FLEET";
	$FEE_SIDE_MENU_HOSTEL = "HOSTEL";
	$FEE_SIDE_MENU_FINE = "FINE";
	$FEE_SIDE_MENU_STATUS = "STATUS";
	$FEE_SIDE_MENU_DAYCOLLECTION = "DAY'S COLLECTION";
	$FEE_SIDE_MENU_CHEQUESTATUS = "CHEQUE STATUS";
	$FEE_SIDE_MENU_RECEIPTCANCELLATION = "RECEIPT CANCELLATION";
	$FEE_SIDE_MENU_HISTORY = "HISTORY";
	//******************************************Fine Module*****************************//
	$FINE_SIDE_MENU_LATEFEEDEFINITIONS = "LATE FEE DEFINITIONS";
	$FINE_SIDE_MENU_CATEGORY = "CATEGORY";
	$FINE_SIDE_MENU_SUB_CATEGORY = "SUB CATEGORY";
	$FINE_SIDE_MENU_ALLOCATION= "ALLOCATION";
	//******************************************HOSTEL Module*****************************//
	$HOSTEL_SIDE_MENU_INFRASTRUCTURE = "INFRASTRUCTURE";
	$HOSTEL_SIDE_MENU_ADDHOSTEL = "ADD HOSTEL";
	$HOSTEL_SIDE_MENU_ROOMNUMBERDEFINITIONS = "ROOM NUMBER DEFINITIONS";
	$HOSTEL_SIDE_MENU_ROOMTYPE= "ROOM TYPE";
	$HOSTEL_SIDE_MENU_ROOMTYPEMAP = "ROOM TYPE MAP";
	$HOSTEL_SIDE_MENU_RESOURCESENTRY = "RESOURCES ENTRY";
	$HOSTEL_SIDE_MENU_APPLIANCES = "APPLIANCES";
	$HOSTEL_SIDE_MENU_RESOURCES = "RESOURCES";
	$HOSTEL_SIDE_MENU_RESOURCEALLOCATION = "RESOURCE ALLOCATION";
	$HOSTEL_SIDE_MENU_ROOM_ALLOCATION = "ROOM ALLOCATION";
	$HOSTEL_SIDE_MENU_SUB_ROOMALLOCATION = "ROOM ALLOCATION";
	
	$HOSTEL_SIDE_MENU_REPORT="REPORT";
	$HOSTEL_SIDE_MENU_RESOURCE_DETAILS="RESOURCE DETAILS";
	$HOSTEL_SIDE_MENU_USERS_DETAILS="USERS DETAILS";
	//******************************************Fleet Module*****************************//
	$FLEET_SIDE_MENU_USER_CONFIRMATION = "CONFIRMATION";
	$FLEET_SIDE_MENU_USER = "LIST OF OPTED STUDENTS ";
	$FLEET_SIDE_MENU_INFRASTRUCTURE = "INFRASTRUCTURE";
	$FLEET_SIDE_MENU_SELECT = "SELECT";
	$FLEET_SIDE_MENU_BASIC = "BASIC";
	$FLEET_SIDE_MENU_INSURANCE= "INSURANCE";
	$FLEET_SIDE_MENU_FC = "FITNESS CERTIFICATE";
	$FLEET_SIDE_MENU_NEW = "NEW";
	$FLEET_SIDE_MENU_STAFF = "STAFF";
	$FLEET_SIDE_MENU_SELECT = "SELECT";
	$FLEET_SIDE_MENU_BASIC = "BASIC";
	$FLEET_SIDE_MENU_EDUCATION = "EDUCATION";
	$FLEET_SIDE_MENU_FINANCE = "FINANCE";
	$FLEET_SIDE_MENU_PERSONAL = "PERSONAL";
	$FLEET_SIDE_MENU_EXPERIENCE = "EXPERIENCE";
	$FLEET_SIDE_MENU_VENDOR = "VENDOR";
	$FLEET_SIDE_MENU_CATEGORY= "CATEGORY";
	$FLEET_SIDE_MENU_SELECT = "SELECT";
	$FLEET_SIDE_MENU_BASICINFORMATION = "BASIC INFORMATION";
	$FLEET_SIDE_MENU_CATEGORYMAP = "CATEGORY MAP";
	$FLEET_SIDE_MENU_NEW = "NEW";
	$FLEET_SIDE_MENU_ROUTE = "ROUTE";
	$FLEET_SIDE_MENU_ROUTES = "ROUTES";
	$FLEET_SIDE_MENU_BOARDINGPOINT = "BOARDING POINT";
	$FLEET_SIDE_MENU_ARRANGEBOARDINGPOINT = "ARRANGE BOARDING POINT";
	$FLEET_SIDE_MENU_TRIPSDEFINITION = "TRIPS DEFINITION";
	$FLEET_SIDE_MENU_EXPENSES = "EXPENSES";
	$FLEET_SIDE_MENU_FUEL= "FUEL";
	$FLEET_SIDE_MENU_REPAIR = "REPAIR";
	$FLEET_SIDE_MENU_TRIPSHEET = "TRIPSHEET";
	$FLEET_SIDE_MENU_TRIP_SHEET = "TRIPSHEET";
	$FLEET_SIDE_MENU_MAPPING = "MAPPING";
	$FLEET_SIDE_MENU_ALLOCATION = "ALLOCATION";
	$FLEET_SIDE_MENU_RESOURCEALLOCATION = "ALLOCATION";
	$FLEET_SIDE_MENU_FINELATEFEE= "FINE & LATE FEE";
	$FLEET_SIDE_MENU_F_ALLOCATION= "ALLOCATION";
	$FLEET_SIDE_MENU_REPORTS = "REPORTS";
	$FLEET_SIDE_MENU_TRIPSHEET_D = "TRIPSHEET DATEWISE";
	$FLEET_SIDE_MENU_FUELEXPENSE = "FUEL EXPENSE";
	$FLEET_SIDE_MENU_REPAIREXPENSE = "REPAIR EXPENSE";
	$FLEET_SIDE_MENU_YEARLYINCOME = "YEARLY INCOME";
	//******************************************Library Module*****************************//
	$LIBRARY_SIDE_MENU_DEFINITION = "DEFINITION";
	$LIBRARY_SIDE_MENU_BOOKCATEGORY = "BOOK CATEGORY";
	$LIBRARY_SIDE_MENU_BOOKDETAIL = "BOOK DETAIL";
	$LIBRARY_SIDE_MENU_STUDENTLIBRARY= "STUDENT LIBRARY";
	$LIBRARY_SIDE_MENU_ISSUELIBRARYCARD = "ISSUE LIBRARY CARD";
	$LIBRARY_SIDE_MENU_ISSUEBOOK = "ISSUE BOOK";
	$LIBRARY_SIDE_MENU_RETURNBOOK = "RETURN BOOK";
	$LIBRARY_SIDE_MENU_FACULTYLIBRARY = "FACULTY LIBRARY";
	$LIBRARY_SIDE_MENU_ISSUELIBRARYCARD = "ISSUE LIBRARY CARD";
	$LIBRARY_SIDE_MENU_ROOM_ISSUEBOOK = "ISSUE BOOK";
	$LIBRARY_SIDE_MENU_SUB_RETURNBOOK = "RETURN BOOK";
	//******************************************Placements Module*****************************//
	$PLACEMENT_SIDE_MENU_DEFINITION = "DEFINITION";
	$PLACEMENT_SIDE_MENU_ROUNDS = "NO OF ROUNDS";
	$PLACEMENT_SIDE_MENU_COMPANIES = "COMPANIES";
	$PLACEMENT_SIDE_MENU_ROUNDSCOMPANYMAP= "ROUNDS & COMPANY MAP";
	$PLACEMENT_SIDE_MENU_RECRUITMENTDETAILS = "RECRUITMENT DETAILS";
	$PLACEMENT_SIDE_MENU_ELIGIBLESTUDENTS = "ELIGIBLE STUDENTS";
	$PLACEMENT_SIDE_MENU_STATISTICS = "STATISTICS";
	//*********************************Alumni Menu*********************************************//
	$ALUMNI_SIDE_MENU_STUDENT = "STUDENT";
	$ALUMNI_SIDE_MENU_SELECT_STUDENT = "SELECT";
	$ALUMNI_SIDE_MENU_BASIC = "BASIC INFO";
	$ALUMNI_SIDE_MENU_FAMILY = "FAMILY INFO";
	$ALUMNI_SIDE_MENU_PERSONAL = "PERSONAL INFO";
	$ALUMNI_SIDE_MENU_SSLC = "SSLC";
	$ALUMNI_SIDE_MENU_PUC = "PRE UNIVERSITY";
	$ALUMNI_SIDE_MENU_DIPLOMA = "DIPLOMA";
	$ALUMNI_SIDE_MENU_CURRICULAR = "CURRICULAR ACTIVITIES";
	$ALUMNI_SIDE_MENU_GENERALINFORMATION = "GENERAL INFORMATION";
	$ALUMNI_SIDE_MENU_REMARKS = "REMARKS";
	$ALUMNI_SIDE_MENU_FEEDBACKFORM = "FEED BACK FORM";
	$ALUMNI_SIDE_MENU_SEMESTERWISEACADEMICS = "SEMESTERWISE ACADEMICS";
	//*********************************Visitors Menu*********************************************//
	$VISITORS_SIDE_MENU_VISITORS = "VISITORS";	
	$VISITORS_SIDE_MENU_ENTRY="ENTRY";
	$VISITORS_SIDE_MENU_EXIT = "EXIT";
	//*********************************Expense Menu*********************************************//
	$EXPENSE_SIDE_MENU_EXPENSE = "EXPENSE";	
	$EXPENSE_SIDE_MENU_CATEGORY="CATEGORY";
	$EXPENSE_SIDE_MENU_EXPENSEENTRY = "EXPENSE ENTRY";
	//*********************************Admissions Menu*********************************************//
	$ADMISSION_SIDE_MENU_APPLICATION = "APPLICATION";
	$ADMISSION_SIDE_MENU_OLLECTAPPLICATIONFEES = "COLLECT APPLICATION FEES";
	$ADMISSION_SIDE_MENU_ISSUEAPPLICATION = "ISSUE APPLICATION";
	$ADMISSION_SIDE_MENU_COLLECTAPPLICATIONFEESANDISSUE  = "COLLECT APPLICATION FEES AND ISSUE ";
	$ADMISSION_SIDE_MENU_RECEIPT_CANCEL = "RECEIPT CANCELLATION";
	$ADMISSION_SIDE_MENU_INFORMATION = "INFORMATION";
	$ADMISSION_SIDE_MENU_SELECT_STUDENT = "SELECT";
	$ADMISSION_SIDE_MENU_BASIC = "BASIC INFO";
	$ADMISSION_SIDE_MENU_FAMILY = "FAMILY INFO";
	$ADMISSION_SIDE_MENU_PERSONAL = "PERSONAL INFO";
	$ADMISSION_SIDE_MENU_SSLC = "SSLC";
	$ADMISSION_SIDE_MENU_PUC = "PRE UNIVERSITY";
	$ADMISSION_SIDE_MENU_DIPLOMA = "DIPLOMA";
	$ADMISSION_SIDE_MENU_DEGREE = "DEGREE";
	$ADMISSION_SIDE_MENU_CURRICULAR = "CURRICULAR ACTIVITIES";
	$ADMISSION_SIDE_MENU_GENERALINFORMATION = "GENERAL INFORMATION";
	$ADMISSION_SIDE_MENU_REMARKS = "REMARKS";
	$ADMISSION_SIDE_MENU_FEEDBACKFORM = "FEED BACK FORM";
	$ADMISSION_SIDE_MENU_ADMISSIONDETAILS = "ADMISSION DETAILS";
	$ADMISSION_SIDE_MENU_FEECONCESSION = "FEE CONCESSION";
	$ADMISSION_SIDE_MENU_CONFIRMADMISSION = "CONFIRM ADMISSION";
	
	//*********************************Regulations Menu*********************************************//
	$REGULATIONS_SIDE_MENU_REGULATIONS = "REGULATIONS";	
	$REGULATIONS_SIDE_MENU_UPDATECURRICULUM="UPDATE CURRICULUM";
	$REGULATIONS_SIDE_MENU_COPYREGULATIONS = "COPY REGULATIONS";
	//*********************************Sandesh*********************************************//
	$ADMIN_SIDE_MENU_COPY_DATA_PREVIOUS_YEAR = "COPY PREVIOUS YEAR DATA";	
	$ADMIN_SIDE_MENU_SEMESTER_SECTIONMAP_QUOTA="SEMESTER SECTION MAP & QUOTA";
	$FEE_SIDE_MENU_COPY_DATA_PREVIOUS_YEAR = "COPY PREVIOUS YEAR DATA";
	$FEE_SIDE_MENU_FEE_DETAILS = "FEE DETAILS";
	
	$FLEET_SIDE_MENU_COPY_DATA_PREVIOUS_YEAR = "COPY PREVIOUS YEAR DATA";
	$FLEET_SIDE_MENU_COPY_FLEET_DETAILS = "FLEET DETAILS";
//*********************************Performance Menu*********************************************//
	$STUDENT = "STUDENT";
	$FACULTY = "FACULTY";
	$INSTITUTE = "INSTITUTE";
	$COURSE = "COURSE";
	$CLASS = "CLASS";
	$DEPARTMENT = "DEPARTMENT";
//******************************Reports Menu**********************************************//


// $REPOTS_ADMIN="ADMIN";  
  $REPORT_SIDE_ACADEMIC_YEAR ="COURSE WORKING DAYS";
  $REPORT_SIDE_ACADEMIC_CALENDER="ACADEMIC CALENDER";
  $REPORT_SIDE_LIST_OF_HOLIDAY="LIST OF HOLIDAYS";
  $REPORT_SIDE_LIST_OF_EVENTS="LIST OF EVENTS";
  $REPORT_SIDE_COURSE_ALLSUBJECT_COURSE="LIST OF USERS";
  $REPORT_SIDE_COURSE_ALL="LIST OF COURSE";
   $REPORT_COURSE_DEPARTMENT="COURSE DEPARTMENT";
   $REPORT_SUBJECT_ALL="LIST OF SUBJECT";
   $REPORT_SUBJECT_COURSE="SUBJECT COURSES";
   $REPORT_SUBJECT_SEMESTER="SUBJECT SEMESTER";
  $REPORT_FACULTY_ALL="FACULTY ALL";
  $REPORT_SIDE_FACULTY_DEPARTMENT="FACULTY DEPARTMENT";
  $REPORT__STUDENT_ALL="LIST OF STUDENT";
  $REPORT_STUDENT_DEPARTMENT="STUDENT DEPARTMENT";
  $REPORT_STUDENT_COURSE="STUDENT COURSE";
  $REPORT_NCET_REPORT="NCET REPORT";

  $REPORT_ATTENDACE="ATTENDANCE";
  $REPORT_WEEKLY="WEEKLY";
  $REPORT_MONTHLY="MONTHLY";
  $REPORT_ENROLLNO="ENROLL NO";
  $REPORT_SIDE_COURSE="COUSRE";
  $REPORT_SIDE_COUSRE_DATE ="COURSE DATE";
  $REPORT_DATE_COURSE_FIRST_HOUR="DATE/HOUR - FIRST HOUR";
  $REPORT_SEMESTER="SEMESTER";
  $REPORT_STUDENT_DATE="STUDENT- DATE";
  $REPORT_PERCENTAGE="PERCENTAGE";
  $REPORT_ABSENTEES="ABSENTEES";
  $REPORT_TWODATE_ENROLLNO="TWODATE-ENROLLNO";
  $REPORT_SUBJECTWISE="SUBJECTWISE";
  $REPORT_SUBJECT_STUDENT="SUBJECT STUDENT";
  $REPORT_SUBJECT_STUDENT_HRS="SUBJECT STUDENT-HRS";
  $REPORT_TWODATE_SEMESTER="TWODATE-SEMESTER";
  $REPORT_PENDING="PENDING";
  $REPORT_PENDING_COURSE="PENDING COURSE";
  
  $REPORT_MARKLIST="MARKLIST";
  $REPORT_MARKLIST_ENROLLNO="ENROLL NUM";
  $REPORT_MARKES_CONSOLIDATE="CONSOLIDATE";
  $REPORT_MARKES_CONSOLIDATE_ENROLL="CONSOLIDATE";
  $REPORT_MARKLIST_SUBJECTWISE="SUBJECTWISE";
  $REPORT_FAILURELIST_COURSE="FAILED STUDENTS COURSEWISE";
  $REPORT_FAILURELIST_SUBJECT="FAILED STUDENTS SUBJECTWISE";
  $REPORT_PASS_FAIL_SUBJECT="PASS AND FAIL INFO";
  $REPORT_NUM_ATTEMPTS_SEMWISE="NUM OF ATTEMPTS SEMWISE";
  $REPORT_SEMESTER_RESULT="SEMESTER RESULT";
  $REPORT_MARKLIST_GRADEWISE="MARKLIST GRADEWISE";
  $REPORT_SEMESTER_MARKLIST="SEMESTER MARKLIST";
  
  $REPORT_FACULTY="FACULTY";
  $REPORT_ALL="ALL";
  $REPORT_EMPLOYEENO="EMPLOYEE NUM";
  $REPORT_DEPARTMENT="DEPARTMENT";
  $REPORT_DESIGNATION="DESIGNATION";
  $REPORT_TITLE="TITLE";
  $REPORT_SUBJECT="SUBJECT";
  $REPORT_SUBJECT_HANDLED="SUBJECT HANDLED";
  $REPORT_FINANCE_DETAILS="FINANCE DETAILS";
  $REPORT_FINANCE_DEPARTMENT="FINANCE DEPARTMENT";
  $REPORT_PROFILE="PROFILE";
  $REPORT_TERMINATIONLIST="TERMINATION LIST";
  
  $REPORT_STUDENT="STUDENT";
  $REPORT_CUMULATIVE_RECORD="CUMULATIVE RECORD";
  $REPORT_STUDENT_ENROLLNUM_UNIQUEID="STUDENT ENROLLNUM UNIQUEID";
  $REPORT_STUDENT_CASTE="STUDENT CASTE";
  $REPORT_STUDENT_DEPARTMENT_YEAR="STUDENT DEPARTMENT YEAR";
  $REPORT_STUDENT_COURSE_YEAR="STUDENT COURSE YEAR";
  $REPORT_STUDENT_QUOTA="STUDENT QUOTA";
  $REPORT_STUDENT_AICTE="STUDENT AICTE";
  
 $REPORT_TIMETABLE="TIME TABLE";
  $REPORT_DEPARTMENT="DEPARTMENT";
  $REPORT_COURSE="COURSE";
  $REPORT_SECTION="SECTION";
  $REPORT_FACULTY="FACULTY";
  $REPORT_DATE="DATE";
  $REPORT_INSTITUTE="INSTITUTE";
  $REPORT_DETAILS_TIME_TABLE="DETAILS TIME TABLE";
  
  $REPORT_FLEET="FLEET";
  $REPORT_TRIPSHEET_DATEWISE="TRIPSHEET DATEWISE";
  $REPORT_FUEL_EXPENSE="FUEL EXPENSE";
  $REPORT_REPAIR_EXPENSE="REPAIR EXPENSE";
  $REPORT_YEARLY_INCOME="YEARLY INCOME";
  
 $REPORT_HOSTEL="HOSTEL";
  $REPORT_HOSTEL_LIST="LIST";
  $REPORT_HOSTEL_ENROLLNO="ENROLLNO";
  $REPORT_HOSTEL_NAME="NAME";
  $REPORT_HOSTEL_ROOMTYPE="ROOMTYPE";
  $REPORT_HOSTEL_ROOMTYPE_MAP="ROOMTYPE MAP";
  $REPORT_HOSTEL_APPLIANCES="APPLIANCES";
  $REPORT_HOSTEL_RESOURCES="RESOURCES";
  $REPORT_HOSTEL_MAINTAINANCE="MAINTANANCE";
  $REPORT_HOSTEL_CAPACITY="CAPACITY";
  
  $REPORT_PLACEMENT = "PLACEMENT";
  $REPORT_COMPANY_DETAILS="COMPANY DETAILS";
  $REPORT_PLACEMENT_COMPANY_DATE="PLACEMENT COMPANY DATE";
  $REPORT_PLACEMENT_STATISTICS="PLACEMENT STATISTICS";
  
 $REPORT_FEES="FEES";

  $REPORT_FEE_ENROLLNO="ENROLLNO";
  $REPORT_FEE_SEMESTERWISE="SEMESTERWISE";
  $REPORT_FEE_RECEIPT="RECEIPT NO";
  $REPORT_FEE_DATEWISE_COLLECTION="DATEWISE COLLECTION";
  $REPORT_FEE_BETWEE_TWO_DATES="BETWEEN TWO DATES";
  $REPORT_FEE_DEPARTMENTWISE="DEPARTMENTWISE";
  
  $REPORT_CUSTOM="CUSTOM";
  $REPORT_TRANSFER_CERTIFICATE="TRANSFER CERTIFICATE";
  $REPORT_BONAFIED_CERTIFICATE="BONAFIED CERTIFICATE";
  
  $REPORT_SIDE_MENU = "ADMIN";
  $REPORT_DYANAMIC_REPORT = "DYNAMIC REPORT";
  $REPORT_DYANAMIC_STUDENT_REPORT = "STUDENT ";
  
  
?>